# Generated by Django 3.0.3 on 2020-03-13 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('scraped_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=250)),
                ('keyword', models.CharField(max_length=100)),
                ('discussions', models.TextField(blank=True, null=True)),
                ('discussion_date', models.DateTimeField(auto_now_add=True, verbose_name='Discussion date')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
