# Generated by Django 3.0.3 on 2020-03-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='keyword',
            field=models.CharField(default='diag', max_length=100),
            preserve_default=False,
        ),
    ]
