# Generated by Django 3.0.3 on 2020-03-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='research',
            name='discussion_date',
        ),
        migrations.RemoveField(
            model_name='research',
            name='discussions',
        ),
    ]
