# Generated by Django 2.2.9 on 2020-01-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='scraped_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
