# Generated by Django 2.2.9 on 2020-01-20 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0002_auto_20200120_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='scraped_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
