# Generated by Django 3.0.3 on 2020-03-13 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("researches", "0003_discussion"),
    ]

    operations = [
        migrations.RemoveField(model_name="discussion", name="created_by",),
        migrations.AddField(
            model_name="discussion",
            name="created_by",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
