# Generated by Django 3.0.3 on 2020-03-13 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researches', '0004_auto_20200313_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='created_by',
        ),
        migrations.AddField(
            model_name='discussion',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
