# Generated by Django 3.0.3 on 2020-03-17 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("researches", "0012_auto_20200317_0906"),
    ]

    operations = [
        migrations.RemoveField(model_name="recommends", name="recommends",),
        migrations.AddField(
            model_name="recommends",
            name="recommends",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
