# Generated by Django 3.0.3 on 2020-03-17 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researches', '0013_auto_20200317_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommends',
            name='recommends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
