# Generated by Django 3.0.3 on 2020-03-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0017_review_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussionreply',
            options={'ordering': ['-created_on'], 'verbose_name': 'DiscussionReplie'},
        ),
        migrations.AlterModelOptions(
            name='recommends',
            options={'verbose_name': 'Recommend'},
        ),
    ]
