# Generated by Django 3.0.3 on 2020-03-22 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("researches", "0018_auto_20200322_1158"),
    ]

    operations = [
        migrations.RemoveField(model_name="recommends", name="recommends",),
        migrations.AddField(
            model_name="recommends",
            name="recommends",
            field=models.ForeignKey(
                blank=True,
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
