# Generated by Django 3.0.3 on 2020-05-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0023_auto_20200322_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussionreply',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterModelOptions(
            name='recommends',
            options={'verbose_name_plural': 'Recommend'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name_plural': 'Research'},
        ),
    ]
