# Generated by Django 3.0.3 on 2020-08-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0024_auto_20200508_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='abstract',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
